// swift-tools-version: 6.0
// Hangar — native macOS agentic terminal
// SPM declares the two library modules (HangarCore, HangarKit) and their dependencies.
// The Xcode app target lives at /Hangar and is generated by XcodeGen (project.yml).

import PackageDescription

let package = Package(
    name: "Hangar",
    platforms: [
        .macOS(.v15)  // Liquid Glass APIs in 26 are additively available; deployment target on the
                      // Xcode app target is macOS 26 (set in project.yml). The SPM modules build
                      // against 15 so they're usable from CI runners that don't yet have 26.2 SDK.
    ],
    products: [
        .library(name: "HangarCore", targets: ["HangarCore"]),
        .library(name: "HangarKit", targets: ["HangarKit"]),
    ],
    dependencies: [
        .package(url: "https://github.com/migueldeicaza/SwiftTerm", from: "1.2.0"),
        .package(url: "https://github.com/groue/GRDB.swift", from: "7.0.0"),
        // Sparkle is wired via the Xcode app target (project.yml), not the SPM
        // library modules — keeping it out of Package.swift silences an
        // "unused dependency" warning during `swift build`.
    ],
    targets: [
        .target(
            name: "HangarCore",
            dependencies: [
                .product(name: "SwiftTerm", package: "SwiftTerm"),
                .product(name: "GRDB", package: "GRDB.swift"),
            ],
            path: "Sources/HangarCore",
            swiftSettings: [
                .enableExperimentalFeature("StrictConcurrency"),
            ]
        ),
        .target(
            name: "HangarKit",
            dependencies: [
                "HangarCore",
                .product(name: "SwiftTerm", package: "SwiftTerm"),
            ],
            path: "Sources/HangarKit",
            swiftSettings: [
                .enableExperimentalFeature("StrictConcurrency"),
            ]
        ),
        .testTarget(
            name: "HangarCoreTests",
            dependencies: ["HangarCore"],
            path: "Tests/HangarCoreTests"
        ),
        .testTarget(
            name: "HangarKitTests",
            dependencies: ["HangarKit"],
            path: "Tests/HangarKitTests"
        ),
    ]
)
